//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCharbon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppelOffre_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppelOffre_Details()
        {
            this.Association = new HashSet<Association>();
        }
    
        public int id_AppDetails { get; set; }
        public int id_StockPrev { get; set; }
        public int id_appOffre { get; set; }
    
        public virtual Appel_Offre Appel_Offre { get; set; }
        public virtual Stock_Previsionnel Stock_Previsionnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Association> Association { get; set; }
    }
}
