//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCharbon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Association
    {
        public int id_Association { get; set; }
        public string code_A0 { get; set; }
        public int id_AppDetails { get; set; }
    
        public virtual AppelOffre_Details AppelOffre_Details { get; set; }
    }
}
