//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCharbon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Charbon_DB2Entities1 : DbContext
    {
        public Charbon_DB2Entities1()
            : base("name=Charbon_DB2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appel_Offre> Appel_Offre { get; set; }
        public virtual DbSet<AppelOffre_Details> AppelOffre_Details { get; set; }
        public virtual DbSet<Association> Association { get; set; }
        public virtual DbSet<Bateau> Bateau { get; set; }
        public virtual DbSet<Centrale_Stock> Centrale_Stock { get; set; }
        public virtual DbSet<Contrat> Contrat { get; set; }
        public virtual DbSet<Contrat_Details> Contrat_Details { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<Origine> Origine { get; set; }
        public virtual DbSet<Planing_Previsionnel> Planing_Previsionnel { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<station_type> station_type { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<Stock_Previsionnel> Stock_Previsionnel { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<MaVue> MaVue { get; set; }
        public virtual DbSet<VBateau> VBateau { get; set; }
        public virtual DbSet<VContrat> VContrat { get; set; }
        public virtual DbSet<Station_Central_Type> Station_Central_Type { get; set; }
    }
}
